coverage:
  precision: 2
  round: down
  range: 0..100
  status:
    project:
      default:
        target: 90
        threshold: 1
        informational: false
    patch:
      default:
        target: 90
        threshold: 1
        informational: false
comment:
  layout: 'header, diff, files'
  behavior: default
  require_changes: false
